clear
set(0, ...
        defaultTextInterpreter='latex', ...
        defaultAxesTickLabelInterpreter='latex', ...
        defaultAxesFontSize=18, ...
        defaultAxesLabelFontSize=1.4, ...
        defaultAxesTitleFontSize=1.4, ...
        defaultLegendInterpreter='latex', ...
        defaultLegendFontSize=16, ...
        defaultLineLineWidth=3, ...
        defaultLineMarkerSize=12 ...
    );

color = ...
    [
    0.8500 0.3250 0.0980;
    0 0 0;
    0 0.4470 0.7410
    ];

%%

f = @(z,a) z - a;

x = [-1 1];
y = x;

a = (sqrt(3) + 1i * sqrt(2)) / 4;
tol = 1e-14;

%%

n = 100;
point_num_max = ceil(linspace(40, 190, n));

approx_error = zeros(n,1);

for i = 1:n
    fprintf('Step <strong>%i/%i</strong>\n', i, n);

    if exist('sol', 'var')
        sol.PointNumMax = point_num_max(i);
        sol.fitTriang;
    else
        sol = GES( ...
                @(z) f(z,a), ...
                [x; y]', ...
                Tol=tol, ...
                PointNumMax=point_num_max(i) ...
            );
    end

    approx_error(i) = abs(mean(sol.CandPoint(:,1)) - a);
end

%%

fig = figure(Position=[0 0 500 500]);

error_fit = fit(point_num_max', log(approx_error), 'poly1');
coef = coeffvalues(error_fit);

hold on
data_fit = plot( ...
        point_num_max, ...
        exp(error_fit(point_num_max)), ...
        '-r' ...
    );
data = plot( ...
        point_num_max, ...
        approx_error, ...
        '.b' ...
    );
hold off

axis([-Inf Inf -Inf Inf]);

set(gca,...
        YScale='log'...
    );
xlabel('$N_{tr}$');
ylabel('$|z_i - a|$');
legend( ...
        [data data_fit], ...
        'Approximation error', ...
        sprintf('$\\exp(%.2f %.2f N_{tr})$', coef(2), coef(1)) ...
    )